using Microsoft.Extensions.DependencyInjection;
using RESTworld.Business.Mapping;
using RESTworld.Business.Mapping.AutoMapper;
using System;

namespace RESTworld.Testing;

/// <summary>
/// Contains extension methods related to mapping.
/// </summary>
public static class MapperTestConfigurationExtensions
{
    /// <summary>
    /// Adds a Mapper to the <paramref name="builder"/>.
    /// </summary>
    /// <param name="builder">The builder to add the configuration to.</param>
    /// <param name="mapperInstance">An optional mapper instance. If none is provided, it will be automatically generated by the ServiceProvider.</param>
    /// <returns>The <paramref name="builder"/>.</returns>
    public static ITestBuilder WithCrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto, TMapper>(this ITestBuilder builder, TMapper? mapperInstance = null)
        where TMapper : class, ICrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>
    {
        return builder.With(new CrudMapperTestConfiguration<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto, TMapper>(mapperInstance));
    }

    /// <summary>
    /// Adds a Mapper to the <paramref name="builder"/>.
    /// </summary>
    /// <param name="builder">The builder to add the configuration to.</param>
    /// <param name="mapperInstance">An optional mapper instance. If none is provided, it will be automatically generated by the ServiceProvider.</param>
    /// <returns>The <paramref name="builder"/>.</returns>
    public static ITestBuilder WithReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto, TMapper>(this ITestBuilder builder, TMapper? mapperInstance = null)
        where TMapper : class, IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>
    {
        return builder.With(new ReadMapperTestConfiguration<TEntity, TQueryDto, TGetListDto, TGetFullDto, TMapper>(mapperInstance));
    }

    /// <summary>
    /// Adds a Mapper based on AutoMapper to the <paramref name="builder"/>.
    /// </summary>
    /// <param name="builder">The builder to add the configuration to.</param>
    /// <returns>The <paramref name="builder"/>.</returns>
    public static ITestBuilder WithCrudAutoMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>(this ITestBuilder builder)
    {
        return builder.WithCrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto, CrudAutoMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>>();
    }

    /// <summary>
    /// Adds a Mapper based on AutoMapper to the <paramref name="builder"/>.
    /// </summary>
    /// <param name="builder">The builder to add the configuration to.</param>
    /// <returns>The <paramref name="builder"/>.</returns>
    public static ITestBuilder WithReadAutoMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>(this ITestBuilder builder)
    {
        return builder.WithReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto, ReadAutoMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>>();
    }
}

/// <summary>
/// This test configuration can add a Crud Mapper to your tests.
/// </summary>
public class CrudMapperTestConfiguration<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto, TMapper> : ITestConfiguration
    where TMapper : class, ICrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>
{
    private readonly TMapper? _mapperInstance;

    public CrudMapperTestConfiguration(TMapper? mapperInstance = null)
    {
        _mapperInstance = mapperInstance;
    }

    /// <inheritdoc/>
    public void AfterConfigureServices(IServiceProvider provider)
    {
    }

    /// <inheritdoc/>
    public void ConfigureServices(IServiceCollection services)
    {
        if (_mapperInstance is null)
        {
            services.AddSingleton<ICrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>, TMapper>();
            services.AddSingleton<IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>, TMapper>();
            services.AddSingleton<TMapper>();
        }
        else
        {
            services.AddSingleton<ICrudMapper<TEntity, TCreateDto, TQueryDto, TGetListDto, TGetFullDto, TUpdateDto>>(_mapperInstance);
            services.AddSingleton<IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>>(_mapperInstance);
            services.AddSingleton(_mapperInstance);
        }
    }
}

/// <summary>
/// This test configuration can add a Crud Mapper to your tests.
/// </summary>
public class ReadMapperTestConfiguration<TEntity, TQueryDto, TGetListDto, TGetFullDto, TMapper> : ITestConfiguration
    where TMapper : class, IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>
{
    private readonly TMapper? _mapperInstance;

    public ReadMapperTestConfiguration(TMapper? mapperInstance = null)
    {
        _mapperInstance = mapperInstance;
    }
    /// <inheritdoc/>
    public void AfterConfigureServices(IServiceProvider provider)
    {
    }

    /// <inheritdoc/>
    public void ConfigureServices(IServiceCollection services)
    {
        if (_mapperInstance is null)
        {
            services.AddSingleton<IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>, TMapper>();
            services.AddSingleton<TMapper>();
        }
        else
        {
            services.AddSingleton<IReadMapper<TEntity, TQueryDto, TGetListDto, TGetFullDto>>(_mapperInstance);
            services.AddSingleton(_mapperInstance);
        }
    }
}