<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMcp.OData" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\RESTworld\RESTworld.AspNetCore\RESTworld.AspNetCore.csproj" />
        <ProjectReference Include="..\ExampleBlog.Business\ExampleBlog.Business.csproj" />
    </ItemGroup>

</Project>
