<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\RESTworld\RESTworld.Business\RESTworld.Business.csproj" />
        <ProjectReference Include="..\ExampleBlog.Data\ExampleBlog.Data.csproj" />
    </ItemGroup>

</Project>
