<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
        <Authors>wertzui</Authors>
        <PackageProjectUrl>https://github.com/wertzui/RESTworld</PackageProjectUrl>
        <RepositoryUrl>https://github.com/wertzui/RESTworld</RepositoryUrl>
        <VersionPrefix>37.0.1</VersionPrefix>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Nullable>enable</Nullable>
        <PackageIcon>RESTworld-256.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="/" />
        <None Include="../../../logo/RESTworld-256.png" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.OData.ApiExplorer" />
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="AutoMapper.AspNetCore.OData.EFCore" />
        <PackageReference Include="CsvHelper" />
        <PackageReference Include="HAL.AspNetCore.OData" />
        <PackageReference Include="HealthChecks.Kubernetes.Aspire" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
        <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RESTworld.Business\RESTworld.Business.csproj" />
    </ItemGroup>

</Project>
